import type { ServiceCategory } from './types'

export const initialServiceCategories: ServiceCategory[] = [
  {
    kicker: 'Corte',
    title: 'Corte de cabello',
    note: 'Incluye lavado y brushing.',
    accent: 'Precision',
    disclaimer: '',
    order: 1,
    active: true,
    items: [
      { categoryId: '', name: 'Corte', price: '$29.990', order: 1, active: true },
      {
        categoryId: '',
        name: 'Corte + peinado',
        price: '$39.990',
        order: 2,
        active: true,
      },
    ],
  },
  {
    kicker: 'Eventos',
    title: 'Peinados',
    note: 'Incluye lavado y brushing.',
    accent: 'Look final',
    disclaimer: '',
    order: 2,
    active: true,
    items: [
      { categoryId: '', name: 'Ondas', price: '$14.990', order: 1, active: true },
      {
        categoryId: '',
        name: 'Peinado de fiesta',
        price: 'Desde $35.990',
        order: 2,
        active: true,
      },
      {
        categoryId: '',
        name: 'Peinado de novia',
        price: 'Desde $65.990',
        order: 3,
        active: true,
      },
    ],
  },
  {
    kicker: 'Salud capilar',
    title: 'Tratamientos capilares',
    note: 'Incluye lavado y brushing.',
    accent: 'Diagnostico',
    disclaimer: '',
    order: 3,
    active: true,
    items: [
      {
        categoryId: '',
        name: 'Tratamiento Inebrya',
        price: '$30.990',
        order: 1,
        active: true,
      },
      {
        categoryId: '',
        name: 'Tratamiento K18',
        price: '$38.990',
        order: 2,
        active: true,
      },
      {
        categoryId: '',
        name: 'Tratamiento Truss',
        price: '$38.990',
        order: 3,
        active: true,
      },
      {
        categoryId: '',
        name: 'Botox Capilar S/M',
        price: '$40.990',
        order: 4,
        active: true,
      },
      {
        categoryId: '',
        name: 'Botox Capilar L/XL',
        price: '$45.990',
        order: 5,
        active: true,
      },
    ],
  },
  {
    kicker: 'Disciplina',
    title: 'Alisado',
    note: 'Incluye fluido antihumedad.',
    accent: 'Anti frizz',
    disclaimer:
      'Valor sujeto a evaluación según largo y cantidad de cabello.',
    order: 4,
    active: true,
    items: [
      { categoryId: '', name: 'Corto', price: '$60.000', order: 1, active: true },
      { categoryId: '', name: 'Medio', price: '$80.000', order: 2, active: true },
      { categoryId: '', name: 'Largo', price: '$95.000', order: 3, active: true },
      {
        categoryId: '',
        name: 'Extra largo',
        price: '$110.000',
        order: 4,
        active: true,
      },
    ],
  },
  {
    kicker: 'Colorimetria',
    title: 'Color',
    note: 'Incluye lavado nutritivo y brushing.',
    accent: 'Personalizado',
    disclaimer:
      'Si tu retoque tiene mas de 1 mes de crecimiento, se aplica un cargo adicional de $10.000 por cada mes extra.',
    order: 5,
    active: true,
    items: [
      { categoryId: '', name: 'Cintillo', price: '$25.990', order: 1, active: true },
      {
        categoryId: '',
        name: 'Retoque crecimiento',
        price: '$40.990',
        order: 2,
        active: true,
      },
      {
        categoryId: '',
        name: 'Color global S',
        price: '$53.990',
        order: 3,
        active: true,
      },
      {
        categoryId: '',
        name: 'Color global M',
        price: '$59.990',
        order: 4,
        active: true,
      },
      {
        categoryId: '',
        name: 'Color global L',
        price: '$69.990',
        order: 5,
        active: true,
      },
      {
        categoryId: '',
        name: 'Color global XL',
        price: '$79.990',
        order: 6,
        active: true,
      },
      {
        categoryId: '',
        name: 'Falso crecimiento',
        price: '$25.990 / $38.990',
        order: 7,
        active: true,
      },
    ],
  },
  {
    kicker: 'Mechas',
    title: 'Iluminacion y mechas',
    note: 'Incluye tratamiento profesional y peinado.',
    accent: 'Brillo',
    disclaimer: '',
    order: 6,
    active: true,
    items: [
      {
        categoryId: '',
        name: 'Mechas creativas',
        price: 'Desde $130.990',
        order: 1,
        active: true,
      },
      {
        categoryId: '',
        name: 'Mechas con superaclarante',
        price: 'Desde $100.990',
        order: 2,
        active: true,
      },
    ],
  },
  {
    kicker: 'Rizadas',
    title: 'Cabello rizado',
    note: 'Incluye lavado nutritivo.',
    accent: 'Definicion',
    disclaimer: '',
    order: 7,
    active: true,
    items: [
      {
        categoryId: '',
        name: 'Servicio rizadas S/M',
        price: '$25.990',
        order: 1,
        active: true,
      },
      {
        categoryId: '',
        name: 'Servicio rizadas L/XL',
        price: '$39.990',
        order: 2,
        active: true,
      },
    ],
  },
]
